ALTER TABLE "cases" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "cases" ALTER COLUMN "priority" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "cases" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "cases" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "contacts" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "contacts" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "emails" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "emails" ALTER COLUMN "is_read" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "emails" ALTER COLUMN "is_replied" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "emails" ALTER COLUMN "is_important" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "emails" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "emails" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "notes" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "notes" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "properties" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "properties" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "shifts" ALTER COLUMN "started_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "shifts" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "shifts" ALTER COLUMN "threads_processed" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "shifts" ALTER COLUMN "emails_processed" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "shifts" ALTER COLUMN "drafts_created" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "shifts" ALTER COLUMN "tasks_created" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "shifts" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "shifts" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "tasks" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "tasks" ALTER COLUMN "priority" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "tasks" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "tasks" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "threads" ALTER COLUMN "email_count" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "threads" ALTER COLUMN "is_read" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "threads" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "threads" ALTER COLUMN "updated_at" SET NOT NULL;